### ISSUE TITLE
Z jakiegoś powodu nie działa

### ISSUE THREAD

**Issue by pbiecek** [geneticsMiNIng/BlackBoxOpener#7]
```
library(PBImisc)
library(randomForest)
library(randomForestExplainer)

forest <- randomForest(m2.price ~ ., data = na.omit(apartments[,c(1,2,3,5,7,8,9,12,13,14,15,16)]), localImp=TRUE)

randomForestExplainer::plot_multi_way_importance(forest)
```
wynik
```
Error in importance_frame[importance_frame$no_of_trees > min_no_of_trees,  : 
  incorrect number of dimensions
In addition: Warning message:
In max(importance_frame$no_of_trees) :
  no non-missing arguments to max; returning -Inf
```

**Comment by OlaPaluszynska** [comment]
Powinno być: plot_multi_way_importance(measure_importance(forest)) gdyż argumentem tej funkcji rysującej wykres jest ramka z miarami ważności zmiennych. Podobnie jak w ggRandomForests rozdzieliłam funkcje rysujące wykresy od funkcji produkujących dane żeby: 1) można było łatwo robić swoje wykresy na podstawie tych samych danych oraz 2) żeby te dane nie były generowane kilka razy (w niektórych przypadkach to chwilę trwa).

Niezależnie od tego był inny błąd, teraz jest już nowa wersja.
